[package]
name = "hcpl_fft"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/THE-nio/hcpl"
license = "MIT"

[dependencies]
hcpl_algebra = { path = "../hcpl_algebra" }
# Maybe this can be generalised to cover both FFTs and NTTs
hcpl_complex = { path = "../hcpl_complex" }