[package]
name = "hcpl_union_find"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/THE-nio/hcpl"
license = "MIT"

[dependencies]
hcpl_algebra = { path = "../hcpl_algebra", optional = true }

[features]
tagged = ["dep:hcpl_algebra"]
