[package]
name = "hcpl_number_theory"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/THE-nio/hcpl"
license = "MIT"

[dependencies]
hcpl_algebra = { path = "../hcpl_algebra" }
hcpl_integer = { path = "../hcpl_integer" }
